name: 01-Building-Block
on: push

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Say HEllo
              run: echo "Hello, World"
    echo-goodbye:
        runs-on: ubuntu-latest
        steps:
            - name: Success Steps
              run: |
                echo "I will succeed"
                exit 0
            - name: Say-goodbye
              run: echo "goodbye!"
